[build]
  publish = "staticfiles"
  command = "python manage.py collectstatic --noinput && python manage.py migrate"

[build.environment]
  PYTHON_VERSION = "3.11"
  DJANGO_SETTINGS_MODULE = "school_management.settings"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  DEBUG = "False"
  DJANGO_SETTINGS_MODULE = "school_management.settings"
