# Generated by Django 4.2.7 on 2025-10-01 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(default='EduManager', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system/')),
                ('adresse_etablissement', models.TextField(blank=True)),
                ('telephone_etablissement', models.CharField(blank=True, max_length=15)),
                ('email_etablissement', models.EmailField(blank=True, max_length=254)),
                ('duree_session', models.PositiveIntegerField(default=30)),
                ('tentatives_connexion_max', models.PositiveIntegerField(default=5)),
                ('smtp_server', models.CharField(blank=True, max_length=100)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=100)),
                ('smtp_password', models.CharField(blank=True, max_length=100)),
                ('smtp_use_tls', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paramètres Système',
                'verbose_name_plural': 'Paramètres Système',
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('adresse', models.TextField(blank=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('notifications_email', models.BooleanField(default=True)),
                ('notifications_messages', models.BooleanField(default=True)),
                ('notifications_notes', models.BooleanField(default=True)),
                ('derniere_connexion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('nombre_connexions', models.PositiveIntegerField(default=0)),
                ('compte_active', models.BooleanField(default=True)),
                ('mot_de_passe_temporaire', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('SUCCESS', 'Succès'), ('ERROR', 'Erreur'), ('NEW_MESSAGE', 'Nouveau message'), ('NEW_GRADE', 'Nouvelle note'), ('SCHEDULE_CHANGE', 'Changement emploi du temps'), ('ACCOUNT_CREATED', 'Compte créé'), ('PASSWORD_RESET', 'Mot de passe réinitialisé')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('lue', models.BooleanField(default=False)),
                ('url_action', models.URLField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_message', models.CharField(choices=[('ADMIN_TO_ALL', 'Admin vers Tous'), ('ADMIN_TO_TEACHER', 'Admin vers Enseignant'), ('ADMIN_TO_STUDENT', 'Admin vers Étudiant'), ('STUDENT_TO_TEACHER', 'Étudiant vers Enseignant'), ('STUDENT_TO_ADMIN', 'Étudiant vers Admin'), ('TEACHER_TO_ADMIN', 'Enseignant vers Admin')], max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('lu', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('pour_tous_enseignants', models.BooleanField(default=False)),
                ('pour_tous_etudiants', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_connexion', models.DateTimeField(default=django.utils.timezone.now)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('succes', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_connexion'],
            },
        ),
    ]
