# Generated by Django 4.2.7 on 2025-10-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parametressysteme_profilutilisateur_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='notifications_email',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='notifications_messages',
        ),
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='notifications_notes',
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='dernier_mot_de_passe',
            field=models.CharField(blank=True, help_text='Dernier mot de passe défini (pour affichage admin)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='langue',
            field=models.CharField(default='fr', max_length=10),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='theme',
            field=models.CharField(default='light', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='nombre_connexions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
